export default defineEventHandler(async () => {
  return [
    {
      name: "Galaxy S25",
      brand: "Samsung",
      description:
        "The latest flagship smartphone from Samsung. Highlighted features: advanced AI capabilities, industry-leading 200MP camera, and a stunning Dynamic AMOLED 2X display.",
      price: 1099.99,
      stock: 200,
      specifications: {
        Display: "6.8-inch Dynamic AMOLED 2X, 120Hz, HDR10+",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "200MP Main, 12MP Ultrawide, 10MP Telephoto",
        Battery: "5000 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "AI Integration",
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "5G Connectivity",
      ],
      pros: [
        "Best-in-class display",
        "Versatile and powerful camera system",
        "Rich software features with long-term support",
      ],
      cons: ["Very high price", "Software can feel bloated to some users"],
    },
    {
      name: "Pixel 10",
      brand: "Google",
      description:
        "Google's new smartphone. Main features: powerful new Tensor G5 chip for unmatched AI experiences, exceptional computational photography, and a clean, intelligent Android interface.",
      price: 999.99,
      stock: 300,
      specifications: {
        Display: "6.7-inch LTPO OLED, 120Hz",
        Processor: "Google Tensor G5",
        RAM: "12GB",
        Storage: "256GB",
        Camera: "50MP Main, 48MP Ultrawide, 12MP Telephoto",
        Battery: "5050 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Advanced AI Integration",
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "5G Connectivity",
        "Exclusive AI Features",
      ],
      pros: [
        "Exceptional camera quality with AI enhancements",
        "Clean Android software with instant updates",
        "Unique and helpful AI features",
      ],
      cons: [
        "Tensor chip may not benchmark as high as competitors",
        "Hardware design can be polarizing",
      ],
    },
    {
      name: "iPhone 17",
      brand: "Apple",
      description:
        "The latest iPhone from Apple. It features a new sleek design, the incredibly powerful A19 Bionic chip for pro-level performance, and a more advanced Pro camera system.",
      price: 1199.99,
      stock: 150,
      specifications: {
        Display: "6.9-inch Super Retina XDR OLED, ProMotion",
        Processor: "Apple A19 Bionic",
        RAM: "12GB",
        Storage: "1TB",
        Camera: "48MP Main, 12MP Ultrawide, 12MP Telephoto",
        Battery: "4500 mAh",
        "Operating System": "iOS 19",
      },
      features: [
        "Face ID",
        "Waterproof (IP68)",
        "Wireless Charging (MagSafe)",
        "5G Connectivity",
        "LIDAR Scanner",
      ],
      pros: [
        "Extremely powerful and efficient A19 Bionic chip",
        "Seamless and user-friendly ecosystem",
        "High-quality build materials and design",
      ],
      cons: [
        "Very expensive",
        "Lack of customization in iOS",
        "Requires proprietary chargers and accessories",
      ],
    },
    {
      name: "OnePlus 14",
      brand: "OnePlus",
      description:
        "Experience smooth performance with the new OnePlus 14. Main features: a breathtaking 144Hz Fluid AMOLED display, blazing-fast charging, and a clean, customizable OxygenOS.",
      price: 899.99,
      stock: 250,
      specifications: {
        Display: "6.7-inch Fluid AMOLED, 144Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "18GB",
        Storage: "512GB",
        Camera: "108MP Main, 16MP Ultrawide, 8MP Telephoto",
        Battery: "5200 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Ultra-fast Warp Charging",
        "5G Connectivity",
        "Alert Slider",
      ],
      pros: [
        "Blazing-fast performance and charging",
        "Clean and smooth OxygenOS",
        "High refresh rate display for a fluid experience",
      ],
      cons: [
        "Camera performance can be a step behind top-tier flagships",
        "Brand has a less consistent software support history",
      ],
    },
    {
      name: "Xiaomi 15 Pro",
      brand: "Xiaomi",
      description:
        "Xiaomi's latest flagship. Highlighted features: a stunning professional-grade display co-engineered with Leica, a massive 1-inch camera sensor, and hyper-fast charging.",
      price: 949.99,
      stock: 220,
      specifications: {
        Display: "6.73-inch LTPO AMOLED, 1-120Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "1TB",
        Camera: "1-inch 50MP Main, 50MP Ultrawide, 50MP Telephoto",
        Battery: "5100 mAh",
        "Operating System": "Android 16 with HyperOS",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "HyperCharge (120W)",
        "5G Connectivity",
        "IR Blaster",
      ],
      pros: [
        "Professional-grade camera co-engineered with Leica",
        "Extremely fast wired and wireless charging",
        "Top-tier performance at a competitive price",
      ],
      cons: [
        "HyperOS can be heavy and contain ads",
        "Global availability can be limited initially",
      ],
    },
    {
      name: "Sony Xperia 1 VI",
      brand: "Sony",
      description:
        "A creator-focused smartphone. Its main strength is the professional-grade camera system with a unique continuous optical zoom and a 4K HDR OLED display.",
      price: 1299.99,
      stock: 100,
      specifications: {
        Display: "6.5-inch 4K HDR OLED, 120Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera:
          "48MP Main, 12MP Ultrawide, 12MP Telephoto with continuous zoom",
        Battery: "5000 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "5G Connectivity",
        "3.5mm Headphone Jack",
        "Dedicated Camera Shutter Button",
      ],
      pros: [
        "Professional-grade camera controls and features",
        "Stunning 4K HDR display",
        "Headphone jack and expandable storage",
      ],
      cons: [
        "Very tall and narrow design isn't for everyone",
        "Software updates can be slower than competitors",
        "High price point",
      ],
    },
    {
      name: "Asus ROG Phone 9",
      brand: "Asus",
      description:
        "The ultimate gaming smartphone. Unmatched performance with a special gaming-tuned processor, a high-refresh-rate screen, and ultrasonic AirTrigger controls.",
      price: 1499.99,
      stock: 80,
      specifications: {
        Display: "6.78-inch AMOLED, 165Hz",
        Processor: "Snapdragon 8 Gen 4 for Gaming",
        RAM: "24GB",
        Storage: "1TB",
        Camera: "50MP Main, 13MP Ultrawide",
        Battery: "6000 mAh with 65W fast charging",
        "Operating System": "Android 16",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Splash Resistant",
        "Ultrasonic AirTriggers",
        "5G Connectivity",
        "Dual USB-C Ports",
        "Vapor Chamber Cooling",
      ],
      pros: [
        "Unmatched gaming performance",
        "Innovative gaming-specific features (AirTriggers, cooling)",
        "Massive battery and fast charging",
      ],
      cons: [
        "Bulky and heavy design",
        "Camera system is not a priority",
        "Very niche and expensive",
      ],
    },
    {
      name: "Motorola Edge 50 Pro",
      brand: "Motorola",
      description:
        "A stylish phone with a clean Android experience. Highlighted features: a beautiful pOLED display with a high refresh rate and a near-stock Android for smooth operation.",
      price: 699.99,
      stock: 350,
      specifications: {
        Display: "6.67-inch pOLED, 144Hz",
        Processor: "Snapdragon 8s Gen 3",
        RAM: "12GB",
        Storage: "512GB",
        Camera: "50MP Main, 13MP Ultrawide, 10MP Telephoto",
        Battery: "4500 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "5G Connectivity",
        "Ready For Platform",
      ],
      pros: [
        "Clean, near-stock Android software",
        "Stylish design with a comfortable feel",
        "Competitive price for the features",
      ],
      cons: [
        "Fewer years of promised OS updates than Google or Samsung",
        "Camera performance can be inconsistent",
      ],
    },
    {
      name: "Nokia X60",
      brand: "Nokia",
      description:
        "A durable and reliable smartphone with a focus on longevity. Main features: robust build quality, guaranteed multi-year OS and security updates, and a large battery.",
      price: 599.99,
      stock: 400,
      specifications: {
        Display: "6.7-inch OLED, 120Hz",
        Processor: "Snapdragon 7+ Gen 3",
        RAM: "8GB",
        Storage: "256GB",
        Camera: "108MP Main, 13MP Ultrawide",
        Battery: "5000 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP67)",
        "5G Connectivity",
        "Long-term OS Updates",
      ],
      pros: [
        "Durable build quality",
        "Guaranteed long-term software and security updates",
        "Affordable price point",
      ],
      cons: [
        "Mid-range processor performance",
        "Camera is good but not great",
        "Lacks premium features like wireless charging",
      ],
    },
    {
      name: "Oppo Find X8 Pro",
      brand: "Oppo",
      description:
        "Innovative camera technology in a sleek package. Its strength lies in its custom MariSilicon imaging NPU for stunning photos and videos, especially in low light.",
      price: 1199.99,
      stock: 180,
      specifications: {
        Display: "6.82-inch LTPO AMOLED, 120Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "Dual 50MP Main, 50MP Periscope Telephoto",
        Battery: "5400 mAh",
        "Operating System": "Android 16 with ColorOS",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "SuperVOOC Flash Charge",
        "5G Connectivity",
        "MariSilicon X Imaging NPU",
      ],
      pros: [
        "Excellent camera system, especially in low light",
        "Beautiful and unique design",
        "Very fast charging speeds",
      ],
      cons: [
        "ColorOS is a heavy skin on Android",
        "Availability can be limited in some regions",
        "Premium price",
      ],
    },
    {
      name: "Vivo X100 Pro+",
      brand: "Vivo",
      description:
        "Pushing the boundaries of mobile photography. Highlighted features: a massive 200MP periscope telephoto lens with Zeiss optics and advanced image processing.",
      price: 1399.99,
      stock: 120,
      specifications: {
        Display: "6.78-inch LTPO AMOLED, 120Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "24GB",
        Storage: "1TB",
        Camera: "200MP Telephoto, 50MP Main, 50MP Ultrawide",
        Battery: "5500 mAh",
        "Operating System": "Android 16 with Funtouch OS",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Fast Wireless Charging",
        "5G Connectivity",
        "Zeiss Optics",
      ],
      pros: [
        "Industry-leading telephoto camera capabilities",
        "Stunning display with high brightness",
        "Flagship performance with lots of RAM",
      ],
      cons: [
        "Funtouch OS can be an acquired taste",
        "High price",
        "Global availability is often delayed",
      ],
    },
    {
      name: "Realme GT 6 Pro",
      brand: "Realme",
      description:
        "Flagship performance at an affordable price. Main features: top-tier Snapdragon processor, an ultra-bright display, and one of the fastest charging solutions on the market.",
      price: 799.99,
      stock: 300,
      specifications: {
        Display: "6.78-inch AMOLED, 144Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "50MP Main, 50MP Telephoto, 8MP Ultrawide",
        Battery: "5800 mAh",
        "Operating System": "Android 16 with Realme UI",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Splash Resistant",
        "UltraDart Charging (150W)",
        "5G Connectivity",
        "Stainless Steel Vapor Cooling",
      ],
      pros: [
        "Flagship-level performance for a mid-range price",
        "Extremely fast charging",
        "Bright and fluid display",
      ],
      cons: [
        "Realme UI can be cluttered",
        "Camera performance is good but not at the level of top flagships",
        "Build materials are less premium",
      ],
    },
    {
      name: "Huawei P70 Pro",
      brand: "Huawei",
      description:
        "A focus on camera innovation and design. Its main strength is the variable aperture main camera and advanced XMAGE imaging engine for artistic photography.",
      price: 1099.99,
      stock: 130,
      specifications: {
        Display: "6.8-inch LTPO OLED, 120Hz",
        Processor: "Kirin 9010",
        RAM: "12GB",
        Storage: "512GB",
        Camera: "50MP Variable Aperture Main, 48MP Telephoto, 12.5MP Ultrawide",
        Battery: "5050 mAh",
        "Operating System": "HarmonyOS 5.0",
      },
      features: [
        "In-display Fingerprint Sensor",
        "3D Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "Satellite Connectivity",
        "Variable Aperture Camera",
      ],
      pros: [
        "Exceptional and innovative camera hardware",
        "Premium and unique design",
        "Satellite connectivity for emergencies",
      ],
      cons: [
        "No Google Mobile Services (GMS)",
        "Limited app availability outside of China",
        "Kirin processor lags behind Snapdragon",
      ],
    },
    {
      name: "Google Pixel 9 Fold",
      brand: "Google",
      description:
        "Google's take on a foldable smartphone. Highlighted features: the power of the Tensor G5 chip in a foldable form factor, with all the Pixel-exclusive AI software features.",
      price: 1799.99,
      stock: 90,
      specifications: {
        Display: "7.6-inch internal, 5.8-inch external OLED, 120Hz",
        Processor: "Google Tensor G5",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "48MP Main, 10.8MP Ultrawide, 10.8MP Telephoto",
        Battery: "4821 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Water Resistant",
        "Wireless Charging",
        "5G Connectivity",
        "Foldable Display",
        "Tensor AI",
      ],
      pros: [
        "Clean foldable software experience from Google",
        "Powerful Tensor AI features",
        "Compact and usable front display",
      ],
      cons: [
        "Extremely high price",
        "Durability concerns inherent to foldables",
        "Battery life may be a concern",
      ],
    },
    {
      name: "Samsung Galaxy Z Fold 7",
      brand: "Samsung",
      description:
        "The next generation of Samsung's premier foldable. Its main feature is the large, immersive inner display for unparalleled multitasking and productivity on the go.",
      price: 1899.99,
      stock: 110,
      specifications: {
        Display: "7.6-inch Dynamic AMOLED 2X internal, 6.2-inch external",
        Processor: "Snapdragon 8 Gen 4 for Galaxy",
        RAM: "16GB",
        Storage: "1TB",
        Camera: "50MP Main, 12MP Ultrawide, 10MP Telephoto",
        Battery: "4600 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IPX8)",
        "Wireless Charging",
        "5G Connectivity",
        "Foldable Display",
        "S Pen Support",
      ],
      pros: [
        "Unmatched multitasking on a large foldable screen",
        "S Pen support for productivity",
        "Refined and durable design",
      ],
      cons: [
        "Extremely expensive",
        "Inner screen is still fragile",
        "Bulky and heavy when folded",
      ],
    },
    {
      name: "Samsung Galaxy Z Flip 7",
      brand: "Samsung",
      description:
        "A stylish and compact foldable phone. Its main strength is its portability and the large, functional cover screen for quick interactions without unfolding the device.",
      price: 999.99,
      stock: 280,
      specifications: {
        Display:
          "6.7-inch Dynamic AMOLED 2X internal, 3.4-inch Super AMOLED external",
        Processor: "Snapdragon 8 Gen 4 for Galaxy",
        RAM: "12GB",
        Storage: "512GB",
        Camera: "12MP Main, 12MP Ultrawide",
        Battery: "3900 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IPX8)",
        "Wireless Charging",
        "5G Connectivity",
        "Foldable Display",
        "Flex Mode",
      ],
      pros: [
        "Stylish, compact, and portable design",
        "Large and functional cover screen",
        "Flex Mode enables unique camera angles",
      ],
      cons: [
        "Battery life is average at best",
        "Durability of the folding screen is a concern",
        "Camera system is not as advanced as slab flagships",
      ],
    },
    {
      name: "Microsoft Surface Duo 4",
      brand: "Microsoft",
      description:
        "A dual-screen device for productivity. Its key feature is the dual-screen setup that allows for superior multitasking and running two apps side-by-side.",
      price: 1599.99,
      stock: 70,
      specifications: {
        Display: "Two 6.5-inch AMOLED screens",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "50MP Main, 12MP Ultrawide",
        Battery: "4800 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Face Recognition",
        "Water Resistant",
        "5G Connectivity",
        "Dual-Screen Multitasking",
      ],
      pros: [
        "Excellent for side-by-side multitasking",
        "Thin and premium hardware design",
        "Optimized for Microsoft's productivity suite",
      ],
      cons: [
        "No external display",
        "Camera is not a primary focus",
        "Software can still have bugs related to the dual-screen setup",
      ],
    },
    {
      name: "Fairphone 6",
      brand: "Fairphone",
      description:
        "A sustainable and repairable smartphone. Its main strength is its modular design, allowing users to easily repair and upgrade components, promoting longevity.",
      price: 799.99,
      stock: 150,
      specifications: {
        Display: "6.5-inch OLED",
        Processor: "Snapdragon 7s Gen 2",
        RAM: "8GB",
        Storage: "256GB",
        Camera: "50MP Main, 50MP Ultrawide",
        Battery: "4200 mAh, replaceable",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Splash Resistant",
        "5G Connectivity",
        "Modular Repairable Design",
        "Replaceable Battery",
      ],
      pros: [
        "Sustainable and ethical manufacturing",
        "Easily repairable with modular parts",
        "Long software support and replaceable battery",
      ],
      cons: [
        "Mid-range specs for a relatively high price",
        "Not as durable or water-resistant as other phones",
        "Design is functional rather than stylish",
      ],
    },
    {
      name: "Nothing Phone (3)",
      brand: "Nothing",
      description:
        "A phone with a unique transparent design. Its highlighted features are the Glyph interface for notifications and the clean, minimalist Nothing OS.",
      price: 549.99,
      stock: 400,
      specifications: {
        Display: "6.7-inch LTPO OLED, 120Hz",
        Processor: "Snapdragon 8s Gen 3",
        RAM: "12GB",
        Storage: "256GB",
        Camera: "50MP Main, 50MP Ultrawide",
        Battery: "4800 mAh",
        "Operating System": "Android 16 with Nothing OS",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Splash Resistant",
        "Wireless Charging",
        "5G Connectivity",
        "Glyph Interface",
      ],
      pros: [
        "Unique and eye-catching transparent design",
        "Clean and minimalist Nothing OS",
        "Glyph interface is a unique notification system",
      ],
      cons: [
        "Performance is good but not top-of-the-line",
        "Camera is capable but not exceptional",
        "Brand is still new and relatively unproven",
      ],
    },
    {
      name: "CAT S70",
      brand: "CAT",
      description:
        "A rugged smartphone built for tough environments. Its main strength is its extreme durability, certified with IP68/IP69K and MIL-STD-810H ratings.",
      price: 649.99,
      stock: 180,
      specifications: {
        Display: "6.5-inch FHD+, Gorilla Glass Victus",
        Processor: "Snapdragon 695",
        RAM: "6GB",
        Storage: "128GB",
        Camera: "48MP Main, 8MP Ultrawide",
        Battery: "5500 mAh",
        Rating: "IP68/IP69K, MIL-STD-810H",
        "Operating System": "Android 16",
      },
      features: [
        "Rear-mounted Fingerprint Sensor",
        "Waterproof (IP68/IP69K)",
        "MIL-STD-810H Compliant",
        "Thermal Imaging Camera",
        "Push-to-Talk Button",
      ],
      pros: [
        "Extremely rugged and durable",
        "Integrated thermal imaging camera",
        "Very long battery life",
      ],
      cons: [
        "Very bulky and heavy",
        "Low-end processor and specs",
        "Not designed for general consumer use",
      ],
    },
    {
      name: "Razer Phone 4",
      brand: "Razer",
      description:
        "Another iteration of a gaming-focused phone. Its key features are the high-refresh-rate IGZO display and powerful front-facing speakers for an immersive gaming experience.",
      price: 1199.99,
      stock: 90,
      specifications: {
        Display: "6.6-inch IGZO IPS, 144Hz",
        Processor: "Snapdragon 8 Gen 4",
        RAM: "16GB",
        Storage: "512GB",
        Camera: "64MP Main, 13MP Ultrawide",
        Battery: "5000 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Side-mounted Fingerprint Sensor",
        "Splash Resistant",
        "Wireless Charging",
        "5G Connectivity",
        "Front-facing Stereo Speakers",
        "Vapor Chamber Cooling",
      ],
      pros: [
        "High-refresh-rate display is great for gaming",
        "Loud and clear front-facing stereo speakers",
        "Gaming-focused performance",
      ],
      cons: [
        "Design is dated and bulky",
        "Camera performance is average",
        "Battery life can suffer during long gaming sessions",
      ],
    },
    {
      name: "LG Velvet 3",
      brand: "LG",
      description:
        "A stylish and sleek phone making a comeback. Its main strength is its premium design and focus on a high-quality multimedia experience.",
      price: 699.99,
      stock: 200,
      specifications: {
        Display: "6.8-inch P-OLED",
        Processor: "Snapdragon 7 Gen 3",
        RAM: "8GB",
        Storage: "256GB",
        Camera: "48MP Main, 8MP Ultrawide, 5MP Depth",
        Battery: "4300 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "In-display Fingerprint Sensor",
        "Face Recognition",
        "Waterproof (IP68)",
        "Wireless Charging",
        "5G Connectivity",
        "Stylus Support",
      ],
      pros: [
        "Sleek and stylish design",
        "Good multimedia experience with P-OLED display",
        "Stylus support adds versatility",
      ],
      cons: [
        "Mid-range processor for the price",
        "LG's future in the mobile market is uncertain",
        "Software updates may be slow",
      ],
    },
    {
      name: "BlackBerry Key3",
      brand: "BlackBerry",
      description:
        "A modern smartphone with a physical keyboard. Its main feature is the iconic BlackBerry physical keyboard for a superior typing experience and productivity.",
      price: 899.99,
      stock: 120,
      specifications: {
        Display: "4.5-inch IPS LCD with keyboard",
        Processor: "Snapdragon 7 Gen 3",
        RAM: "8GB",
        Storage: "256GB",
        Camera: "48MP Main, 13MP Ultrawide",
        Battery: "4500 mAh",
        "Operating System": "Android 16",
      },
      features: [
        "Fingerprint Sensor (in spacebar)",
        "Face Recognition",
        "Physical QWERTY Keyboard",
        "5G Connectivity",
        "Programmable Convenience Key",
      ],
      pros: [
        "Excellent physical keyboard for typing",
        "Good security and productivity features",
        "Unique design stands out",
      ],
      cons: [
        "Small screen size for media consumption",
        "Mid-range processor",
        "Camera is not a primary focus",
      ],
    },
  ];
});
